name: pre-commit

on: [push]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - uses: actions/setup-go@v5
        with:
          go-version: "1.21.4"

      - name: Install abigen
        run: go install github.com/ethereum/go-ethereum/cmd/abigen@v1.13.14

      - uses: pre-commit/action@v3.0.0
